#pragma once

#include <7zip/IDecl.h>

// Creates format guids following the 7zip convention of Format_*, e.g. Format_Zip, Format_BZip2
// For some reason, the 7zib library doesn't define these for us

#define DECL_ARCHIVE_FORMAT(name, id) \
	DEFINE_GUID(Format_ ## name, k_7zip_GUID_Data1, k_7zip_GUID_Data2, k_7zip_GUID_Data3_Common, \
	0x10, 0x00, 0x00, 0x01, 0x10, id, 0x00, 0x00);

DECL_ARCHIVE_FORMAT(Zip, 0x1);
DECL_ARCHIVE_FORMAT(BZip2, 0x2);
DECL_ARCHIVE_FORMAT(Rar4, 0x3);
DECL_ARCHIVE_FORMAT(Arj, 0x4);
DECL_ARCHIVE_FORMAT(Lzw, 0x5);
DECL_ARCHIVE_FORMAT(Lzh, 0x6);
DECL_ARCHIVE_FORMAT(SevenZip, 0x7);
DECL_ARCHIVE_FORMAT(Cab, 0x8);
DECL_ARCHIVE_FORMAT(Nsis, 0x9);
DECL_ARCHIVE_FORMAT(Lzma, 0xA);
DECL_ARCHIVE_FORMAT(Lzma86, 0xB);
DECL_ARCHIVE_FORMAT(XZ, 0xC);
DECL_ARCHIVE_FORMAT(Ppmd, 0xD);
DECL_ARCHIVE_FORMAT(Rar, 0xCC);
DECL_ARCHIVE_FORMAT(TE, 0xCF);
DECL_ARCHIVE_FORMAT(UEFIc, 0xD0);
DECL_ARCHIVE_FORMAT(UEFIs, 0xD1);
DECL_ARCHIVE_FORMAT(SquashFS, 0xD2);
DECL_ARCHIVE_FORMAT(CramFS, 0xD3);
DECL_ARCHIVE_FORMAT(APM, 0xD4);
DECL_ARCHIVE_FORMAT(Mslz, 0xD5);
DECL_ARCHIVE_FORMAT(Flv, 0xD6);
DECL_ARCHIVE_FORMAT(Swf, 0xD7);
DECL_ARCHIVE_FORMAT(Swfc, 0xD8);
DECL_ARCHIVE_FORMAT(Ntfs, 0xD9);
DECL_ARCHIVE_FORMAT(Fat, 0xDA);
DECL_ARCHIVE_FORMAT(Mbr, 0xDB);
DECL_ARCHIVE_FORMAT(Vhd, 0xDC);
DECL_ARCHIVE_FORMAT(PE, 0xDD);
DECL_ARCHIVE_FORMAT(Elf, 0xDE);
DECL_ARCHIVE_FORMAT(MachO, 0xDF);
DECL_ARCHIVE_FORMAT(Udf, 0xE0);
DECL_ARCHIVE_FORMAT(Xar, 0xE1);
DECL_ARCHIVE_FORMAT(Mub, 0xE2);
DECL_ARCHIVE_FORMAT(Hfs, 0xE3);
DECL_ARCHIVE_FORMAT(Dmg, 0xE4);
DECL_ARCHIVE_FORMAT(Compound, 0xE5);
DECL_ARCHIVE_FORMAT(Wim, 0xE6);
DECL_ARCHIVE_FORMAT(Iso, 0xE7);
DECL_ARCHIVE_FORMAT(Chm, 0xE9);
DECL_ARCHIVE_FORMAT(Split, 0xEA);
DECL_ARCHIVE_FORMAT(Rpm, 0xEB);
DECL_ARCHIVE_FORMAT(Deb, 0xEC);
DECL_ARCHIVE_FORMAT(Cpio, 0xED);
DECL_ARCHIVE_FORMAT(Tar, 0xEE);
DECL_ARCHIVE_FORMAT(GZip, 0xEF);
